### PR TITLE
Bump up IRIS version to 0.10.0SNAPSHOT

### PR DESCRIPTION
**Pull request by shyamsuchak**

### CODE REVIEW

**Comment by junejosheeraz** [comment]
I believe you forgot to update 0.9.0.qualifier to 0.10.0.qualifier for DSL plugins? Could you please update that and run build locally on your machine on master to make sure it works fine

**Comment by junejosheeraz** [comment]
@shyamsuchak ?

**Comment by shyamsuchak** [comment]
I will change 0.9.0.qualifier to  0.10.0.qualifier and run the build.

**Comment by shyamsuchak** [comment]
@junejosheeraz Build has completed successfully on my machine . Please merge

**Comment by junejosheeraz** [comment]
Can you please let everyone know that they have to sync their workspaces top master and work on 0.10.0-SNAPSHOT and backpatch everything they need to release with R16. Also we need to plan work for Technology DEV to now use 0.10.0-SNAPSHOT for development.

Regards

**Pull request merged**
